/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package fr.ufrsciencestech.panier.view;

import fr.ufrsciencestech.panier.controler.Controleur;
import java.util.Observable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sltctom
 */
public class VuePanierV2 extends javax.swing.JFrame implements VueG {

    private DefaultTableModel model;
    
    /** Creates new form VuePanierV2 */
    public VuePanierV2() {
        initComponents();

        // Créez un modèle de tableau personnalisé avec les colonnes "Produit", "Origine", "Prix", "Quantité"
        model = new DefaultTableModel();
        model.addColumn("Produit");
        model.addColumn("Origine");
        model.addColumn("Prix");
        model.addColumn("Quantité");

        // Définissez le modèle pour le tableau jTable1
        jTable1.setModel(model);

        // Ajoutez vos données au modèle (vous pouvez remplacer ces données par les vôtres)
        model.addRow(new Object[]{"Produit 1", "Origine 1", 10.0, 5});
        model.addRow(new Object[]{"Produit 2", "Origine 2", 15.0, 3});
        // Ajoutez d'autres lignes de données ici
    }
    
    public void mettreAJourTableau(Object[][] donnees) {
    // Supprimez toutes les lignes du modèle actuel
    while (model.getRowCount() > 0) {
        model.removeRow(0);
    }
    
    // Ajoutez de nouvelles lignes de données au modèle
    for (Object[] ligne : donnees) {
        model.addRow(ligne);
    }
}


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void run() {
        VuePanierV2 vue = new VuePanierV2();
        vue.setVisible(true);

        // Exemple de mise à jour du tableau
        Object[][] nouvellesDonnees = {
            {"Nouveau Produit", "Nouvelle Origine", 20.0, 7},
            // Ajoutez d'autres données ici
        };
        vue.mettreAJourTableau(nouvellesDonnees);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable m, Object o) {
        System.out.println("update");
    }

    @Override
    public void addControleur(Controleur c) {
        System.out.println("controleur");
    }

}
