/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package fr.ufrsciencestech.panier.view;

import fr.ufrsciencestech.panier.controler.Controleur;
import fr.ufrsciencestech.panier.model.panier.Panier;
import java.util.Observable;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sltctom
 */
public class VuePanierV2 extends javax.swing.JFrame implements VueG {

    private DefaultTableModel model;
    
    /** Creates new form VuePanierV2 */
    public VuePanierV2() {
        initComponents();

        // Créez un modèle de tableau personnalisé avec les colonnes "Produit", "Origine", "Prix", "Quantité"
        model = new DefaultTableModel();
        model.addColumn("Produit");
        model.addColumn("Origine");
        model.addColumn("Prix");
        model.addColumn("Quantité");
        model.addColumn("");

        // Définissez le modèle pour le tableau jTable1
        jTable1.setModel(model);

        // Ajoutez vos données au modèle (vous pouvez remplacer ces données par les vôtres)
        model.addRow(new Object[]{"Produit 1", "Origine 1", 10.0, 5});
        model.addRow(new Object[]{"Produit 2", "Origine 2", 15.0, 3});
        // Ajoutez d'autres lignes de données ici
    }
    
    public void mettreAJourTableau(Object[][] donnees) {
        // Supprimez toutes les lignes du modèle actuel
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
    
        // Ajoutez de nouvelles lignes de données au modèle
        for (Object[] ligne : donnees) {
            model.addRow(ligne);
        }
    }
    
    @Override
    public void update(Observable m, Object o) {
        this.mettreAJourTableau(((Panier) o).toObject());
    }

    @Override
    public void addControleur(Controleur c) {
        this.add.addActionListener(c);
        this.del.addActionListener(c);
        //this.jTable1.addActionListener(c);
    }
    
    public javax.swing.JTable getTab() {
        return jTable1;
    }
    
    public javax.swing.JTextField getTextFieldType() {
        return tf_Type;
    }
    
    /*public void run() {
        VuePanierV2 vue = new VuePanierV2();
        vue.setVisible(true);

        // Exemple de mise à jour du tableau
        Object[][] nouvellesDonnees = {
            {"Nouveau Produit", "Nouvelle Origine", 20.0, 7},
            // Ajoutez d'autres données ici
        };
        vue.mettreAJourTableau(nouvellesDonnees);
    }*/


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        del = new javax.swing.JButton();
        del.setName("del");
        jPanel1 = new javax.swing.JPanel();
        tf_Type = new javax.swing.JTextField();
        tf_Origine = new javax.swing.JTextField();
        tf_Prix = new javax.swing.JTextField();
        tf_Quantite = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        add.setName("add");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        del.setLabel("del");
        getContentPane().add(del, java.awt.BorderLayout.EAST);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new java.awt.GridLayout());

        tf_Type.setText("Orange");
        tf_Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_TypeActionPerformed(evt);
            }
        });
        jPanel1.add(tf_Type);

        tf_Origine.setText("Origine");
        jPanel1.add(tf_Origine);

        tf_Prix.setText("Prix");
        jPanel1.add(tf_Prix);

        tf_Quantite.setText("Quantité");
        jPanel1.add(tf_Quantite);

        add.setLabel("add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void tf_TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_TypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_TypeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton del;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tf_Origine;
    private javax.swing.JTextField tf_Prix;
    private javax.swing.JTextField tf_Quantite;
    private javax.swing.JTextField tf_Type;
    // End of variables declaration//GEN-END:variables

}
